import {
  Leaf,
  Apple,
  Wheat,
  Flame,
  Droplets,
  Package,
  Sprout,
  GlassWater,
  Drumstick,
  Croissant,
  Snowflake,
  Box,
  Utensils,
  Candy,
  Sparkles,
  Heart,
  Home,
  FileText,
  Store,
} from 'lucide-react';

export const GROCERY_CATEGORY_IMAGE_MAP: Record<string, string> = {
  Vegetables: '/category/vegetables.jpeg',
  Fruits: '/category/fruits.jpeg',
  'Grains & Cereals': '/category/grains&cereals.jpg',
  Spices: '/category/spices.webp',
  Beverages: '/category/beverages.jpeg',
  Snacks: '/category/snacks.jpg',
  'Green Grocery': '/category/green-grocery.jpeg',
  Dairy: '/category/Dairy.jpeg',
  Meat: '/category/meat.jpg',
  Bakery: '/category/bakery.webp',
  'Frozen Foods': '/category/frozen-foods.jpg',
  'Canned Goods': '/category/canned-goods.jpeg',
};

export const RETAIL_CATEGORY_IMAGE_MAP: Record<string, string> = {
  'Food Essentials': '/retail/food%20essentials.jpeg',
  Beverages: '/retail/beverages.jpg',
  'Snacks & Confectionery': '/retail/Snacks-Confectionary.jpg',
  'Cleaning Products': '/retail/cleaning%20products.webp',
  'Personal Care': '/retail/beverages.jpg',
  'Household Items': '/retail/beverages.jpg',
  'Paper Products': '/retail/paper%20products.jpeg',
  'General Merchandise': '/retail/general%20merchandize.jpeg',
};

export const CATEGORY_IMAGE_MAP: Record<string, string> = {
  ...GROCERY_CATEGORY_IMAGE_MAP,
  ...RETAIL_CATEGORY_IMAGE_MAP,
};

export const CATEGORY_ICON_MAP: Record<string, React.ReactNode> = {
  Vegetables: <Leaf className="w-7 h-7" />,
  Fruits: <Apple className="w-7 h-7" />,
  'Grains & Cereals': <Wheat className="w-7 h-7" />,
  Spices: <Flame className="w-7 h-7" />,
  Beverages: <Droplets className="w-7 h-7" />,
  Snacks: <Package className="w-7 h-7" />,
  'Green Grocery': <Sprout className="w-7 h-7" />,
  Dairy: <GlassWater className="w-7 h-7" />,
  Meat: <Drumstick className="w-7 h-7" />,
  Bakery: <Croissant className="w-7 h-7" />,
  'Frozen Foods': <Snowflake className="w-7 h-7" />,
  'Canned Goods': <Box className="w-7 h-7" />,
  'Food Essentials': <Utensils className="w-7 h-7" />,
  'Snacks & Confectionery': <Candy className="w-7 h-7" />,
  'Cleaning Products': <Sparkles className="w-7 h-7" />,
  'Personal Care': <Heart className="w-7 h-7" />,
  'Household Items': <Home className="w-7 h-7" />,
  'Paper Products': <FileText className="w-7 h-7" />,
  'General Merchandise': <Store className="w-7 h-7" />,
};

export const CATEGORY_COLOR_MAP: Record<string, string> = {
  Vegetables: 'text-green-700 dark:text-green-400',
  Fruits: 'text-red-600 dark:text-red-400',
  'Grains & Cereals': 'text-amber-700 dark:text-amber-400',
  Spices: 'text-orange-600 dark:text-orange-400',
  Beverages: 'text-blue-600 dark:text-blue-400',
  Snacks: 'text-purple-600 dark:text-purple-400',
  'Green Grocery': 'text-emerald-700 dark:text-emerald-400',
  Dairy: 'text-cyan-600 dark:text-cyan-400',
  Meat: 'text-rose-700 dark:text-rose-400',
  Bakery: 'text-yellow-700 dark:text-yellow-400',
  'Frozen Foods': 'text-sky-600 dark:text-sky-400',
  'Canned Goods': 'text-gray-700 dark:text-gray-400',
  'Food Essentials': 'text-amber-600 dark:text-amber-400',
  'Snacks & Confectionery': 'text-pink-600 dark:text-pink-400',
  'Cleaning Products': 'text-teal-600 dark:text-teal-400',
  'Personal Care': 'text-indigo-600 dark:text-indigo-400',
  'Household Items': 'text-slate-600 dark:text-slate-400',
  'Paper Products': 'text-blue-600 dark:text-blue-400',
  'General Merchandise': 'text-violet-600 dark:text-violet-400',
};
